#
# Copyright (c) 2025. Aziz
#
product.data.format={0},{1},{2},{3},{4},{5}
review.data.format={0},{1}
reports.folder=/home/aziz/IdeaProjects/se21-exam/reports
data.folder=/home/aziz/IdeaProjects/se21-exam/data
temp.folder=/home/aziz/IdeaProjects/se21-exam/temp
report.file=product{0}report.txt
product.data.file=product{0}.csv
reviews.data.file=reviews{0}.csv
temp.file={0}.tmp